### ISSUE TITLE
Python: Traceback

### ISSUE THREAD

**Issue by 23Mounir23** [Naxela/The_Lightmapper#101]
hello, i hope you have a good day, i tried your addon it is very nice, go away brother donot stop often, but often i have this issue, can you help me please.
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-b4e7eb66ea9b5b676f71a0efdb294df2be3c0583\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-b4e7eb66ea9b5b676f71a0efdb294df2be3c0583\addon\utility\build.py", line 95, in prepare_build
    begin_build()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-b4e7eb66ea9b5b676f71a0efdb294df2be3c0583\addon\utility\build.py", line 275, in begin_build
    lightmap.bake()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-b4e7eb66ea9b5b676f71a0efdb294df2be3c0583\addon\utility\cycles\lightmap.py", line 43, in bake
    if bpy.context.scene.view_layers[0].layer_collection.children[collection.name].hide_viewport:
KeyError: 'bpy_prop_collection[key]: key "Collection 5" not found'

location: <unknown location>:-1

**Comment by Naxela** [comment]
Hi and thanks for trying out the addon and for reporting this bug!
I've added a new commit (https://github.com/Naxela/The_Lightmapper/commit/b21e831f7d58e4bbc01fcf8d4e21d78e5f82d0b9) that might fix this issue. 

Can you try and see if it helps?

**Comment by 23Mounir23** [comment]
Thank you @Naxela ,  Yes i can and want to try it , but how i can to add your new added commit to the addon, 😂

**Comment by 23Mounir23** [comment]
hi @Naxela , i tried it , it dosnot work , and there is another thing , sometimes the lightmapper logo stay in the corner even after finish , somtimes as black rectangle , and i think you have to add somthing like downloading bar , because we donot know is it freezing or working , thanks bro you have a very nice job.
the error is :
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 51, in prepare_build
    setGui(1)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 1080, in setGui
    driver["TLM_UI"] = Viewport.ViewportDraw(context, "Building Lightmaps")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\gui\Viewport.py", line 18, in __init__
    image = bpy.data.images[image_name]
KeyError: 'bpy_prop_collection[key]: key "TLM_Overlay.png" not found'

location: <unknown location>:-1

**Comment by Naxela** [comment]
Hi, and thanks for the reply.

It sounds strange that it doesn't work with the collection, do you have a scene (blend file) that you could share where the error occurs?

As for the black box, I will look into that although it usually only occurs when you get other errors.

**Comment by 23Mounir23** [comment]
it is working now bro, thanks, but i founded a new issue, i will add it, by the way, i trying the addon more than 100 time in the day
