### ISSUE TITLE
sequence expected at dimension 1, not 'float'

### ISSUE THREAD

**Issue by 23Mounir23** [Naxela/The_Lightmapper#105]
it is worknig but without applying the denoising, this is the text of issue
Python: Traceback (most recent call last):
  File "C:\Users\mounir\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\mounir\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 95, in prepare_build
    begin_build()
  File "C:\Users\mounir\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 613, in begin_build
    manage_build()
  File "C:\Users\mounir\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 631, in manage_build
    nodes.apply_materials(load_atlas) #From here the name is changed...
  File "C:\Users\mounir\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\The_Lightmapper-master\addon\utility\cycles\nodes.py", line 272, in apply_materials
    baseColorNode.outputs[0].default_value = baseColorValue
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'

location: <unknown location>:-1

**Comment by Naxela** [comment]
Hi,

Can you make a screenshot of your material setup?

**Comment by 23Mounir23** [comment]
![materials](https://user-images.githubusercontent.com/79379609/116877842-2470b400-ac27-11eb-9323-638de2cf1870.jpg)
usually i have more yhan this materials on one object

**Comment by Naxela** [comment]
Oh I see, if you turn on the verbose toggle in the options settings and try to run the lightmapping again, it should say which material it is working with right before you get the error. 

It seems from the error message that one of the color inputs is getting a number (float) / black&white input instead (the grey dot instead of a color vector (yellow dot))
