### ISSUE TITLE
"StructRNA of type Image has been removed" when trying to build lightmaps with default settings

### ISSUE THREAD

**Issue by fearguyQ** [Naxela/The_Lightmapper#113]
Traceback (most recent call last):
  File "C:\Users\carso\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\thelightmapper\addon\utility\gui\Viewport.py", line 54, in draw_image_callback
    bgl.glBindTexture(bgl.GL_TEXTURE_2D, self.image.bindcode)
ReferenceError: StructRNA of type Image has been removed
Traceback (most recent call last):
  File "C:\Users\carso\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\thelightmapper\addon\utility\gui\Viewport.py", line 54, in draw_image_callback
    bgl.glBindTexture(bgl.GL_TEXTURE_2D, self.image.bindcode)
ReferenceError: StructRNA of type Image has been removed

**Comment by Naxela** [comment]
Hi, I'm currently looking itno fixing this, but usually it can be solved by finding the image called TLM_Overlay.png and shift-clicking on the delete image button:

![image](https://user-images.githubusercontent.com/5429817/119239146-8433ee00-bb47-11eb-9026-de7213ba42dc.png)

**Comment by fazckl** [comment]
Hi, I'm having a similar problem. When I open up a new project and only add a plane beneath the cube, enable Lightmapper and build Lightmaps, I get the "Building Lightmaps..." icon in the lower left but nothing happens after that. I tried deleting the image the way you mentioned but that doesn't seem to solve anything.

Earlier I got another error telling me that TLM_Overlay.png could not be found. That disappeared without me knowing what changed. Maybe this is relevant.
