### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "TLM_Overlay.png" not found'

### ISSUE THREAD

**Issue by alancwoo** [Naxela/The_Lightmapper#119]
I am using `Blender 2.93.1` and `TLM 0.5.5.0`

It worked for a moment but now I am running into this error:

```
Python: Traceback (most recent call last):
  File "/Users/REDACTED/Library/Application Support/Blender/2.93/scripts/addons/thelightmapper/addon/operators/tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "/Users/REDACTED/Library/Application Support/Blender/2.93/scripts/addons/thelightmapper/addon/utility/build.py", line 57, in prepare_build
    setGui(1)
  File "/Users/REDACTED/Library/Application Support/Blender/2.93/scripts/addons/thelightmapper/addon/utility/build.py", line 1179, in setGui
    driver["TLM_UI"] = Viewport.ViewportDraw(context, "Building Lightmaps")
  File "/Users/REDACTED/Library/Application Support/Blender/2.93/scripts/addons/thelightmapper/addon/utility/gui/Viewport.py", line 18, in __init__
    image = bpy.data.images[image_name]
KeyError: 'bpy_prop_collection[key]: key "TLM_Overlay.png" not found'

location: <unknown location>:-1
```

I can confirm the file `TLM_Overlay.png` is present, but it semes to be an issue with the key itself.

**Comment by daniele-pelagatti** [comment]
On a fresh installation, Windows 10 PRO, blender 2.93.1, TLM 0.5.5, I can conform this is happening and does not allow me to use the addon.

First time I launched a bake, it worked, but the overlay was solid pink, second time this error happens.
