### ISSUE TITLE
Unable to bake on Blender 3.0

### ISSUE THREAD

**Issue by phoondos** [Naxela/The_Lightmapper#135]
I get this error when trying to bake on Blender 3.0:
`Error: Python: Traceback (most recent call last):
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\build.py", line 91, in prepare_build
    naming_check()
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 18, in init
    set_settings()
  File "C:\Users\phoon\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 590, in set_settings

AttributeError: 'RenderSettings' object has no attribute 'tile_x'

location: <unknown location>:-1`
I also get errors when trying to bake on Blender 2.92, but they're different from these errors, the errors on 2.92 are looking for a png that doesn't exist or something along those lines.

**Comment by kitaedesigns** [comment]
I also get the same error in blender 3.0

![image](https://user-images.githubusercontent.com/23407511/144930592-75df52b0-5f1a-40df-82cb-98503fbd772e.png)

**Comment by Naxela** [comment]
It should be fixed in https://github.com/Naxela/The_Lightmapper/commit/e1e27ee6719473e5ad82f401563830970660c23f (latest master), but I haven't made a new release yet. I'll put a new release in the releases page tomorrow

**Comment by kitaedesigns** [comment]
ok thanks Naxela!

**Comment by Naxela** [comment]
WIP Release: https://github.com/Naxela/The_Lightmapper/releases/tag/0.6

**Comment by ROBYER1** [comment]
I can't seem to install OpenCV with that wip 0.6 version, the install button seems to work, system log prints 'Sucessfully installed OpenCV!' but on restart, opencv isn't enabled in Blender 3.0

**Comment by paperli** [comment]
> I can't seem to install OpenCV with that wip 0.6 version, the install button seems to work, system log prints 'Sucessfully installed OpenCV!' but on restart, opencv isn't enabled in Blender 3.0

Same here. Manually installed opencv but still no luck.

**Comment by ROBYER1** [comment]
Still getting that error with that release, using Blender 3.1.0

**Comment by Naxela** [comment]
@ROBYER1 Thanks for reporting this!

Is this occuring with the WIP release (https://github.com/Naxela/The_Lightmapper/releases/tag/0.6.12) or the latest git commit/green-frontpage-button (https://github.com/Naxela/The_Lightmapper/archive/refs/heads/master.zip)

**Comment by ROBYER1** [comment]
WIP Release that you linked there (latest as of today) tested with the current Blender 3.1.0 version as of today also

**Comment by ROBYER1** [comment]
> @ROBYER1 Thanks for reporting this!
> 
> Is this occuring with the WIP release (https://github.com/Naxela/The_Lightmapper/releases/tag/0.6.12) or the latest git commit/green-frontpage-button (https://github.com/Naxela/The_Lightmapper/archive/refs/heads/master.zip)

Can confirm it works with the latest git zip you linked, could be worth updating the release labelled with 3.1.0 support. I hope Blender stop changing so much that breaks your plugin and thanks for the ongoing support <3

**Comment by Naxela** [comment]
@ROBYER1 Hi, thanks for testing it and reporting back. I've added the latest git as a release: https://github.com/Naxela/The_Lightmapper/releases/tag/0.6.3

Unfortunately, I think it's one of the downsides of supporting the latest Blender version. I know that a lot of addons are beginning to only support the LTS versions, but it's a shame since a lot of nice new features and performance improvements gets implemented with each new release.

**Comment by lucasjinreal** [comment]
bpy.context.render.tile_x = 256
AttributeError: 'Context' object has no attribute 'render'
