### ISSUE TITLE
Denoiser Paths not found

### ISSUE THREAD

**Issue by Simonrazer** [Naxela/The_Lightmapper#149]
Hi! When trying to use external Denoisers, this error shows up: 

OIDN:
```location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] Der Netzwerkpfad wurde nicht gefunden: '\\\\..\\..\\ArmSDK\\oidn-1.4.3.x64.vc14.windows\\bin\\oidnDenoise.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\build.py", line 105, in prepare_build
    begin_build()
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\build.py", line 352, in begin_build
    denoiser = oidn.TLM_OIDN_Denoise(oidnProperties, baked_image_array, dirpath)
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\denoiser\oidn.py", line 20, in __init__
    self.check_binary()
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\denoiser\oidn.py", line 28, in check_binary
    file = os.path.basename(os.path.realpath(oidnPath))
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] Der Netzwerkpfad wurde nicht gefunden: '\\\\..\\..\\ArmSDK\\oidn-1.4.3.x64.vc14.windows\\bin\\oidnDenoise.exe'

location: <unknown location>:-1
```

OptiX:
```location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] Der Netzwerkpfad wurde nicht gefunden: '\\\\..\\..\\ArmSDK\\Denoiser_v2.4\\Denoiser.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\build.py", line 105, in prepare_build
    begin_build()
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\build.py", line 383, in begin_build
    denoiser = optix.TLM_Optix_Denoise(optixProperties, baked_image_array, dirpath)
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\denoiser\optix.py", line 19, in __init__
    self.check_binary()
  File "C:\Users\lpsim\Desktop\ArmSDK\ArmorySDK2205\armsdk/armory\blender\arm\lightmapper\utility\denoiser\optix.py", line 27, in check_binary
    file = os.path.basename(os.path.realpath(optixPath))
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "D:\Programme\Blender293\2.93\python\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] Der Netzwerkpfad wurde nicht gefunden: '\\\\..\\..\\ArmSDK\\Denoiser_v2.4\\Denoiser.exe'

location: <unknown location>:-1
```

`Der Netzwerkpfad wurde nicht gefunden:` translates to "Network-path not found", which confuses me a lot, since I have everything just saved on my desktop.

**Comment by Naxela** [comment]
Hi, thanks for reporting this!

I can't remember if I fixed this in the standalone version, but think the problem is that it usually points to the relative path in Blender (when using the popup browser). I think this should be a Windows issue, but can be solved by copy-pasting the absolute/direct path. In the meantime, I'll see if I can fix it in Armory

**Comment by skyistumbling** [comment]
> I can't remember if I fixed this in the standalone version, but think the problem is that it usually points to the relative path in Blender (when using the popup browser). I think this should be a Windows issue, but can be solved by copy-pasting the absolute/direct path. In the meantime, I'll see if I can fix it in Armory

if so could you please tell us the direct path of Optix to put in here? i've looked all over my computer and haven't been able to find an optix folder despite blender using it. do we have to make a manual installation of optix and have the denoiser use that?
