### ISSUE TITLE
Can't use Xatlas prepack

### ISSUE THREAD

**Issue by Fairplex90** [Naxela/The_Lightmapper#155]
Hi, I am trying to use the Atlas Group method with Xatlas but its giving this error:

> Error: Python: Traceback (most recent call last):
  File "C:\Users\Fairplex\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\thelightmapper\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Fairplex\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\thelightmapper\addon\utility\build.py", line 108, in prepare_build
    prepare.init(self, previous_settings)
  File "C:\Users\Fairplex\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 24, in init
    configure_meshes(self)
  File "C:\Users\Fairplex\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 270, in configure_meshes
    Unwrap_Lightmap_Group_Xatlas_2_headless_call(obj)
  File "C:\Users\Fairplex\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\thelightmapper\addon\utility\utility.py", line 437, in Unwrap_Lightmap_Group_Xatlas_2_headless_call
    scriptsDir = bpy.utils.user_resource('SCRIPTS', "addons")
TypeError: user_resource() takes 1 positional argument but 2 were given

I have tried to completely uninstall Blender and reinstall TLM and Xatlas but I still get this error.

Any help would be appreciated.

**Comment by Naxela** [comment]
Hi, there was some changes to this in Blender 3.2 - I added a possible fix just now: https://github.com/Naxela/The_Lightmapper/commit/85c6532842f53781452f8485257cecf9f4efbe07

Can you test the latest commit to see if it works?
