### ISSUE TITLE
Python errors on bake: "RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect"

### ISSUE THREAD

**Issue by jywarren** [Naxela/The_Lightmapper#156]
Hi, I'm trying to run the final bake step on Blender 3.2.2 on Mac OS 12.5.1 (21G83), and I get a console error, the key line seems to be:"

`RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect`

Is there something I'm obviously doing wrong? Anything I ought to try next? 

Thank you so much, this is an incredible project!

Here is a full error log: 

```
Building lightmaps
Self path: /Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/assets/TLM_Overlay.png
Warning: 1 x Draw window and swap: 15.7161 ms, average: 15.71607590 ms
(3, 2, 2)
No previous material for Material2.002
No Previous material array for: Material2.002
Preparing: UV initiation for object: Material2.002
Traceback (most recent call last):
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/operators/tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/build.py", line 108, in prepare_build
    prepare.init(self, previous_settings)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/cycles/prepare.py", line 24, in init
    configure_meshes(self)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/cycles/prepare.py", line 149, in configure_meshes
    bpy.ops.object.convert(target='MESH')
  File "/Applications/Blender 3.2.2.app/Contents/Resources/3.2/scripts/modules/bpy/ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect
Error: Python: Traceback (most recent call last):
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/operators/tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/build.py", line 108, in prepare_build
    prepare.init(self, previous_settings)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/cycles/prepare.py", line 24, in init
    configure_meshes(self)
  File "/Users/warren/Library/Application Support/Blender/3.2/scripts/addons/thelightmapper/addon/utility/cycles/prepare.py", line 149, in configure_meshes
    bpy.ops.object.convert(target='MESH')
  File "/Applications/Blender 3.2.2.app/Contents/Resources/3.2/scripts/modules/bpy/ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

^CTraceback (most recent call last):
  File "/Applications/Blender 3.2.2.app/Contents/Resources/3.2/scripts/startup/bl_ui/space_statusbar.py", line 10, in draw
    def draw(self, context):
```

**Comment by jywarren** [comment]
It seems to be failing on this step:

https://github.com/Naxela/The_Lightmapper/blob/85c6532842f53781452f8485257cecf9f4efbe07/addon/utility/cycles/prepare.py#L144-L149

**Comment by jywarren** [comment]
And I am able to bake on a simple model like a cube and plane, as in the wiki example.

**Comment by jywarren** [comment]
I wonder if my model is improperly constructed in some way. It's quite complex, imported from another program:

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/24359/188916770-8f2213d7-3905-484d-904d-cb34ebd8dc82.png">

Any advice on how to work with such models, or to convert them in some way?

**Comment by jywarren** [comment]
Thank you for writing back so quickly! Turning off that option didn't help; same result.

https://drive.google.com/file/d/1B7FXu2rZnzIh8rbdBFPkHMSPXKyADfNb/view?usp=sharing

Here is the file -- I tried it in Blender 3.0.1 and it runs without an error, although it seems to have some trouble that I can probably follow tutorials to work through:

<img width="2048" alt="Screen Shot 2022-09-09 at 10 50 45 AM" src="https://user-images.githubusercontent.com/24359/189378777-60cbb89d-71a7-42b4-87d5-62d8fe511c5e.png">

Thank you again!
