### ISSUE TITLE
Lightmapper broken by default

### ISSUE THREAD

**Issue by rpaladin** [Naxela/The_Lightmapper#160]
```
Traceback (most recent call last):
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_bake.py", line 160, in execute
    img = bpy.data.images.new(img_name, rx, ry)
TypeError: BlendDataImages.new(): error with argument 2, "width" -  Function.width expected an int type, not float
Info: Once baked, hit 'Armory Bake - Apply' to pack lightmaps
Error: Python: Traceback (most recent call last):
  File "D:\Blender\Projects\RP\B3D_33\armsdk/armory\blender\arm\props_bake.py", line 160, in execute
    img = bpy.data.images.new(img_name, rx, ry)
TypeError: BlendDataImages.new(): error with argument 2, "width" -  Function.width expected an int type, not float
```

**Comment by rpaladin** [comment]
@Naxela should this issue be closed, since this seems to be on the Armory side? I mistakenly thought this add-on and the one that ships with Armory are the same, even though they're not, so if this issue is still relevant, this issue should be in the Armory repository.
