### ISSUE TITLE
traceback when selecting "build lightmaps" Blender v3.0-v3.4

### ISSUE THREAD

**Issue by mibarbic** [Naxela/The_Lightmapper#163]
Hi there,
I've installed the prerequisites listed in the Wiki and cannot seem to get this plugin to run on my PC.
I've tried Blender v3.0,v3.1,v3.2, and v3.4. All return the same issue even with the default blender scene.
When selecting "Build Lightmaps" I get the following error:
`Error: Python: Traceback (most recent call last):
  File "C:\Users\micanbar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\thelightmapper\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\micanbar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\thelightmapper\addon\utility\build.py", line 97, in prepare_build
    setMode()
  File "C:\Users\micanbar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\thelightmapper\addon\utility\build.py", line 1287, in setMode
    bpy.context.view_layer.objects.active = obj
RuntimeError: Error: ViewLayer 'View Layer' does not contain object 'CalibrationDown'`
Any help appreciated, thank you.

**Comment by Naxela** [comment]
Hi, sorry I didn't see your message until now. Do you by any chance have an object in your scene named 'CalibrationDown' that is either hidden or linked?
