### ISSUE TITLE
Cannot build lightmaps (Blender 3.5)

### ISSUE THREAD

**Issue by prerakpatel** [Naxela/The_Lightmapper#172]
Hi,

I am not much of a coder but for some reason, I keep seeing this error when I click "Build Lightmaps". I have enabled lightmapper for all the visible objects in the scene. I have one plane that I am using with an emissive material as a light source for the scene. The error I keep seeing is below. I want to create this scene with a 'high' or 'production' quality with 1/1 resolution. What am I doing wrong? Can you please help?

Error: Python: Traceback (most recent call last):
  File "C:\Users\Pushkar\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\thelightmapper\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Pushkar\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\thelightmapper\addon\utility\build.py", line 84, in prepare_build
    if check_materials():
  File "C:\Users\Pushkar\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\thelightmapper\addon\utility\build.py", line 1272, in check_materials
    nodes = mat.node_tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'

<img width="1758" alt="Screenshot 2023-05-12 131556" src="https://github.com/Naxela/The_Lightmapper/assets/1120507/afb086e3-1491-4c23-97e0-b86bc07e0bb9">

**Comment by Naxela** [comment]
Hi, thank you for reporting this issue. I'm not entirely sure what the cause is,- but if could you share the scene then I can take a look. Most likely it seems like there might be a material that doesn't have nodes toggled on, but it could also be a new issue caused by Blender 3.5 (I haven't checked the new version too thoroughly yet)

**Comment by JordanRO2** [comment]
Got the same problem at 3.6 

Python: Traceback (most recent call last):
  File "C:\Users\Jordan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Jordan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 84, in prepare_build
    if check_materials():
  File "C:\Users\Jordan\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 1254, in check_materials
    nodes = mat.node_tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'
