### ISSUE TITLE
Bug: Empty Material slot results in Error

### ISSUE THREAD

**Issue by Simonrazer** [Naxela/The_Lightmapper#33]
![Unbenannt](https://user-images.githubusercontent.com/30187223/85034209-21411680-b182-11ea-90be-de74ff617173.PNG)
This setup results in this error:
```
Warning: 1 x Draw Window and Swap: 14.8811 ms, average: 14.88110000 ms
BAKING:!
Traceback (most recent call last):
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\The_Lightmapper-master\Addon\Operators\build.py", line 55, in modal
    bake_run.bake_ordered(self, context, None)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\The_Lightmapper-master\Addon\Utility\bake_run.py", line 62, in bake_ordered
    utility.check_compatible_naming(self)
  File "C:\Users\SK\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\The_Lightmapper-master\Addon\Utility\utility.py", line 63, in check_compatible_naming
    if "_" in slot.material.name:
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
```

**Comment by Naxela** [comment]
Should be resolved in: https://github.com/Naxela/The_Lightmapper/commit/dbd9c9715b0b24c7e3b7d3ca2e860bd19b2d982c
