### ISSUE TITLE
Error on Linux Install: NameError: name 'pip' is not defined

### ISSUE THREAD

**Issue by anfeo** [Naxela/The_Lightmapper#35]
I have the some error on linux install:
`Traceback (most recent call last):
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/Addon/Utility/cfilter.py", line 13, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anfeo/blender281/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/__init__.py", line 31, in <module>
    from . Addon import Operators, Panels, Properties, Preferences, Utility, Keymap
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/Addon/Operators/__init__.py", line 3, in <module>
    from . import build, clean, explore, encode, installopencv, gui, xBake, selection, additional, lighttools
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/Addon/Operators/build.py", line 3, in <module>
    from .. Utility import bake_run
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/Addon/Utility/bake_run.py", line 2, in <module>
    from . import denoise, objectconfig, lightbake, cfilter, encoding, ambientbake, utility
  File "/home/anfeo/.config/blender/2.83/scripts/addons/The_Lightmapper_master/Addon/Utility/cfilter.py", line 16, in <module>
    pip
NameError: name 'pip' is not defined`

**Comment by Naxela** [comment]
Hi, sadly I won't be able to test out Linux for a few weeks - I'll try to have it fixed for 0.2 in a week or two. In the meantime, you can try to see if the 0.3 branch version is working out better for you: https://github.com/Naxela/The_Lightmapper/tree/0.3

**Comment by Naxela** [comment]
Should be resolved in the 0.3 branch.
