### ISSUE TITLE
error install addon

### ISSUE THREAD

**Issue by Zawarud** [Naxela/The_Lightmapper#38]
when i was install the addon give me this problem.
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\DIO\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\The_Lightmapper-master\__init__.py", line 31, in <module>
    from . addon import operators, panels, properties, preferences, utility, keymap
  File "C:\Users\DIO\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\The_Lightmapper-master\addon\preferences\__init__.py", line 3, in <module>
    from . import addon_preferences
  File "C:\Users\DIO\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\The_Lightmapper-master\addon\preferences\addon_preferences.py", line 1, in <module>
    import bpy, thelightmapper
ModuleNotFoundError: No module named 'thelightmapper'
```

**Comment by Naxela** [comment]
Strange, this shouldn't happen - probably an error caused when I merged the branch recently - if you use the latest git now, does it work? : https://github.com/Naxela/The_Lightmapper/archive/master.zip

**Comment by Zawarud** [comment]
yes. ty

**Comment by Naxela** [comment]
Should be fixed in https://github.com/Naxela/The_Lightmapper/commit/356553d51b093f5a739b7c85448e1e663678e215
