### ISSUE TITLE
Error Appears when i try to build a lightmap

### ISSUE THREAD

**Issue by FunkyPixie** [Naxela/The_Lightmapper#41]
I dont know why but when I try to build a lightmap it gives me this error

```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\Funky\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\thelightmapper\addon\operators\tlm.py", line 23, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Funky\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\thelightmapper\addon\utility\build.py", line 70, in prepare_build
    prepare.init(self, previous_settings)
  File "C:\Users\Funky\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 24, in init
    configure_meshes(self)
  File "C:\Users\Funky\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\thelightmapper\addon\utility\cycles\prepare.py", line 89, in configure_meshes
    bpy.ops.object.select_all(action='DESELECT')
  File "D:\SteamLibrary\steamapps\common\Blender\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

location: <unknown location>:-1
```

I'm using the latest version of blender (steam)

**Comment by Naxela** [comment]
Hi, thanks for opening the ticket

It seems strange that it happens, usually this happens when the 3d viewport isn't active, do you have a customized interface setup, or could you provide a screenshot of when it happens?

**Comment by FunkyPixie** [comment]
![blender_rM9FvJDxZ7](https://user-images.githubusercontent.com/5890200/91640261-250bd780-ea14-11ea-984d-bbdfbcac7efc.png)
This is my blender setup

**Comment by Naxela** [comment]
I think I might have figured it out (at least on my end). If you go out of edit mode (and make sure it's in object mode), does it work? It's something I haven't encountered before, although it's probably a good idea to safeguard against that in the addon

**Comment by FunkyPixie** [comment]
hmm yeah it does work now

**Comment by FunkyPixie** [comment]
i feel like there should be something telling the user to not be in edit mode but thats just me

**Comment by Naxela** [comment]
Good to hear that it works now, and as for the edit mode alert I agree. I've added a fix which automatically sets the mode to object mode before baking, so there shouldn't be other context errors: https://github.com/Naxela/The_Lightmapper/commit/fcc235628627d26a77d5f846f2a10addd93fde29

Anyway, thanks for reporting the bug!

**Comment by FunkyPixie** [comment]
no problem
