### ISSUE TITLE
Baking fails if active scene is not named "Scene"

### ISSUE THREAD

**Issue by ivyallie** [Naxela/The_Lightmapper#81]
If the active scene is not named "Scene", the following error occurs when attempting to run Build Lightmaps:
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 95, in prepare_build
    begin_build()
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 300, in begin_build
    denoiser.denoise()
  File "C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\denoiser\integrated.py", line 70, in denoise
    bpy.data.scenes["Scene"].render.filepath = self.image_output_destination + "/" + filename + "_denoised" + file_extension
KeyError: 'bpy_prop_collection[key]: key "Scene" not found'
```

**Comment by Naxela** [comment]
Hi, and thanks for using The Lightmapper and for reporting the bug!

I can confirm the error on my end as well, I'll push a fix later today

Thanks again

**Comment by Naxela** [comment]
Hi, this should be fixed in https://github.com/Naxela/The_Lightmapper/commit/4eefd2e6028f9107295c854524bb31ac33742b9b

**Comment by ivyallie** [comment]
Fix confirmed. Thank you!
