### ISSUE TITLE
Error when baking multiple objects

### ISSUE THREAD

**Issue by Naxela** [Naxela/The_Lightmapper#83]
```Building lightmaps
Self path: C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\assets\TLM_Overlay.png
Warning: 1 x Draw window and swap: 6.8241 ms, average: 6.82409992 ms
No previous material for 01
No previous material for 02
No previous material for 03
No previous material for 19
No previous material for 06
No previous material for 07
No previous material for 12
No previous material for 05
No previous material for 04
No previous material for 13
No previous material for 17
No previous material for 15
No previous material for 16
No previous material for 11
No previous material for 10
No previous material for 09
No previous material for 08
No previous material for 14
No previous material for 18
No Previous material array for: 01
No Previous material array for: 02
No Previous material array for: 03
No Previous material array for: 19
No Previous material array for: 06
No Previous material array for: 07
No Previous material array for: 12
No Previous material array for: 05
No Previous material array for: 04
No Previous material array for: 13
No Previous material array for: 17
No Previous material array for: 15
No Previous material array for: 16
No Previous material array for: 11
No Previous material array for: 10
No Previous material array for: 09
No Previous material array for: 08
No Previous material array for: 14
No Previous material array for: 18
mesh_ensure_tessellation_customdata: warning! Tessellation uvs or vcol data got out of sync, had to reset!
    CD_MTFACE: 0 != CD_MLOOPUV: 4 || CD_MCOL: 0 != CD_MLOOPCOL: 0
mesh_ensure_tessellation_customdata: warning! Tessellation uvs or vcol data got out of sync, had to reset!
    CD_MTFACE: 0 != CD_MLOOPUV: 4 || CD_MCOL: 0 != CD_MLOOPCOL: 0
mesh_ensure_tessellation_customdata: warning! Tessellation uvs or vcol data got out of sync, had to reset!
    CD_MTFACE: 0 != CD_MLOOPUV: 4 || CD_MCOL: 0 != CD_MLOOPCOL: 1
mesh_ensure_tessellation_customdata: warning! Tessellation uvs or vcol data got out of sync, had to reset!
    CD_MTFACE: 0 != CD_MLOOPUV: 3 || CD_MCOL: 0 != CD_MLOOPCOL: 1
mesh_ensure_tessellation_customdata: warning! Tessellation uvs or vcol data got out of sync, had to reset!
    CD_MTFACE: 0 != CD_MLOOPUV: 2 || CD_MCOL: 0 != CD_MLOOPCOL: 0
Python: Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 85, in prepare_build
    prepare.init(self, previous_settings)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\cycles\prepare.py", line 24, in init
    configure_meshes(self)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\cycles\prepare.py", line 268, in configure_meshes
    mainNode = outputNode.inputs[0].links[0].from_node
IndexError: tuple index out of range

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\operators\tlm.py", line 52, in invoke
    build.prepare_build(self, False)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\build.py", line 85, in prepare_build
    prepare.init(self, previous_settings)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\cycles\prepare.py", line 24, in init
    configure_meshes(self)
  File "C:\Users\Alex\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\The_Lightmapper-master\addon\utility\cycles\prepare.py", line 268, in configure_meshes
    mainNode = outputNode.inputs[0].links[0].from_node
IndexError: tuple index out of range

location: <unknown location>:-1
```

From post: https://blenderartists.org/t/the-lightmapper-v0-3/1247359/61

**Comment by Naxela** [comment]
Solved: https://blenderartists.org/t/the-lightmapper-v0-3/1247359/65
